package handler

import (
	"fmt"
	"net/http"
	"strings"
)

// handleLinuxSetupScript returns an interactive bash script that configures
// Kerberos SSO on Linux machines: krb5.conf, browser policies, and testing.
func (h *Handler) handleLinuxSetupScript(w http.ResponseWriter, r *http.Request) {
	krbCfg, _ := h.getKerberosConfig()
	ldapCfg, _ := h.getLDAPConfigDecrypted()

	realm := h.getKRB5Realm()
	hostname := h.cfg.Hostname
	basePath := h.cfg.BasePath
	deploymentName := h.cfg.DeploymentName

	// Derive KDC from LDAP URL if available
	kdc := ""
	if ldapCfg != nil && ldapCfg.URL != "" {
		kdc = ldapCfg.URL
		kdc = strings.TrimPrefix(kdc, "ldaps://")
		kdc = strings.TrimPrefix(kdc, "ldap://")
		kdc = strings.Split(kdc, ":")[0] // strip port
	}
	if krbCfg != nil && krbCfg.ServiceHostname != "" && kdc == "" {
		kdc = krbCfg.ServiceHostname
	}

	// Derive domain from realm
	domain := strings.ToLower(realm)

	script := linuxSetupScript(hostname, realm, kdc, domain, basePath, deploymentName)

	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="setup-sso-%s.sh"`, strings.ToLower(deploymentName)))
	w.Write([]byte(script))
}

func linuxSetupScript(hostname, realm, kdc, domain, basePath, deploymentName string) string {
	shEsc := func(s string) string {
		return strings.ReplaceAll(strings.ReplaceAll(s, "'", "'\\''"), "\"", "\\\"")
	}

	return `#!/usr/bin/env bash
# ============================================================================
#  SimpleAuth — Linux Kerberos SSO Setup Script
#  Generated by SimpleAuth (` + shEsc(deploymentName) + `)
#
#  This script configures your Linux machine for seamless Kerberos SSO:
#    1. Installs Kerberos client packages
#    2. Configures /etc/krb5.conf
#    3. Configures browser policies for Firefox, Chrome, Chromium, Edge, Brave
#    4. Tests the configuration
#
#  Usage:  sudo bash setup-sso-` + strings.ToLower(shEsc(deploymentName)) + `.sh
#
#  Safe to re-run. Backs up existing configs before overwriting.
# ============================================================================

set -euo pipefail

# --- Configuration (baked in from SimpleAuth) ---
REALM="` + shEsc(realm) + `"
KDC="` + shEsc(kdc) + `"
DOMAIN="` + shEsc(domain) + `"
AUTH_HOSTNAME="` + shEsc(hostname) + `"
AUTH_BASE_PATH="` + shEsc(basePath) + `"
DEPLOYMENT="` + shEsc(deploymentName) + `"

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

banner() {
  echo ""
  echo -e "${CYAN}${BOLD}  ════════════════════════════════════════════${NC}"
  echo -e "${CYAN}${BOLD}       SimpleAuth  Linux  SSO  Setup${NC}"
  echo -e "${CYAN}${BOLD}  ════════════════════════════════════════════${NC}"
  echo ""
  echo -e "  Realm:     ${BOLD}${REALM}${NC}"
  echo -e "  KDC:       ${BOLD}${KDC}${NC}"
  echo -e "  Domain:    ${BOLD}${DOMAIN}${NC}"
  echo -e "  Auth URL:  ${BOLD}https://${AUTH_HOSTNAME}${AUTH_BASE_PATH}${NC}"
  echo ""
}

info()    { echo -e "  ${BLUE}[INFO]${NC}  $*"; }
ok()      { echo -e "  ${GREEN}[  OK]${NC}  $*"; }
warn()    { echo -e "  ${YELLOW}[WARN]${NC}  $*"; }
fail()    { echo -e "  ${RED}[FAIL]${NC}  $*"; }
step()    { echo ""; echo -e "  ${BOLD}[$1] $2${NC}"; echo ""; }

# --- Root check ---
if [[ $EUID -ne 0 ]]; then
  fail "This script must be run as root (use sudo)"
  exit 1
fi

ACTUAL_USER="${SUDO_USER:-$USER}"

banner

# ═══════════════════════════════════════════
#  Step 1: Install Kerberos client packages
# ═══════════════════════════════════════════
step "1/4" "Install Kerberos client packages"

install_packages() {
  if command -v apt-get &>/dev/null; then
    info "Detected Debian/Ubuntu (apt)"
    DEBIAN_FRONTEND=noninteractive apt-get install -y krb5-user libpam-krb5 2>/dev/null || apt-get install -y krb5-user
  elif command -v dnf &>/dev/null; then
    info "Detected Fedora/RHEL 8+ (dnf)"
    dnf install -y krb5-workstation
  elif command -v yum &>/dev/null; then
    info "Detected RHEL/CentOS (yum)"
    yum install -y krb5-workstation
  elif command -v pacman &>/dev/null; then
    info "Detected Arch Linux (pacman)"
    pacman -S --noconfirm krb5
  elif command -v zypper &>/dev/null; then
    info "Detected openSUSE (zypper)"
    zypper install -y krb5-client
  elif command -v apk &>/dev/null; then
    info "Detected Alpine (apk)"
    apk add --no-cache krb5
  else
    warn "Unknown package manager — please install krb5 client manually"
    warn "  Debian/Ubuntu: apt install krb5-user"
    warn "  RHEL/Fedora:   dnf install krb5-workstation"
    warn "  Arch:          pacman -S krb5"
  fi
}

if command -v kinit &>/dev/null; then
  ok "Kerberos client already installed ($(which kinit))"
else
  install_packages
  if command -v kinit &>/dev/null; then
    ok "Kerberos client installed"
  else
    fail "Failed to install Kerberos client"
    exit 1
  fi
fi

# ═══════════════════════════════════════════
#  Step 2: Configure /etc/krb5.conf
# ═══════════════════════════════════════════
step "2/4" "Configure Kerberos (/etc/krb5.conf)"

KRB5_CONF="/etc/krb5.conf"
DOMAIN_LOWER=$(echo "$DOMAIN" | tr '[:upper:]' '[:lower:]')

if [[ -f "$KRB5_CONF" ]]; then
  if grep -qi "$REALM" "$KRB5_CONF" 2>/dev/null; then
    ok "krb5.conf already contains realm $REALM"
  else
    BACKUP="${KRB5_CONF}.backup.$(date +%Y%m%d%H%M%S)"
    info "Backing up existing krb5.conf → $BACKUP"
    cp "$KRB5_CONF" "$BACKUP"
  fi
fi

info "Writing krb5.conf for realm $REALM"
cat > "$KRB5_CONF" << KRBEOF
# Generated by SimpleAuth ($DEPLOYMENT) — $(date -u +%Y-%m-%dT%H:%M:%SZ)
[libdefaults]
    default_realm = ${REALM}
    dns_lookup_realm = false
    dns_lookup_kdc = true
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    rdns = false
    default_ccache_name = KEYRING:persistent:%{uid}

[realms]
    ${REALM} = {
        kdc = ${KDC}
        admin_server = ${KDC}
    }

[domain_realm]
    .${DOMAIN_LOWER} = ${REALM}
    ${DOMAIN_LOWER} = ${REALM}
KRBEOF

ok "krb5.conf written"

# ═══════════════════════════════════════════
#  Step 3: Configure browser policies
# ═══════════════════════════════════════════
step "3/4" "Configure browser Kerberos policies"

# The negotiate-auth URI pattern
AUTH_URI="https://${AUTH_HOSTNAME}"

configure_firefox() {
  local name="$1"
  local dir="$2"
  local found=false

  if [[ -d "$(dirname "$dir")" ]] || command -v "$name" &>/dev/null; then
    mkdir -p "$dir"
    local policy_file="${dir}/policies.json"

    if [[ -f "$policy_file" ]]; then
      # Merge: add our URI to existing SPNEGO/Delegated arrays if not already present
      if command -v python3 &>/dev/null; then
        python3 -c "
import json, sys
try:
    with open('${policy_file}') as f:
        p = json.load(f)
except:
    p = {}
pol = p.setdefault('policies', {})
auth = pol.setdefault('Authentication', {})
for key in ['SPNEGO', 'Delegated']:
    arr = auth.get(key, [])
    if not isinstance(arr, list):
        arr = [arr]
    if '${AUTH_URI}' not in arr:
        arr.append('${AUTH_URI}')
    auth[key] = arr
auth.setdefault('AllowNonFQDN', {})['SPNEGO'] = True
with open('${policy_file}', 'w') as f:
    json.dump(p, f, indent=2)
" 2>/dev/null && ok "$name: merged ${AUTH_URI} into existing ${policy_file}" && found=true
      fi

      if ! $found; then
        warn "$name: python3 not available, overwriting ${policy_file}"
      fi
    fi

    if ! $found; then
      cat > "$policy_file" << FFEOF
{
  "policies": {
    "Authentication": {
      "SPNEGO": ["${AUTH_URI}"],
      "Delegated": ["${AUTH_URI}"],
      "AllowNonFQDN": {
        "SPNEGO": true
      }
    }
  }
}
FFEOF
      ok "$name: policy written → ${policy_file}"
    fi
    found=true
  fi

  if ! $found; then
    info "$name: not installed (skipped)"
  fi
}

configure_chromium_based() {
  local name="$1"
  local policy_dir="$2"
  # Each deployment gets its own file — Chrome merges all .json files in managed/
  local policy_file="${policy_dir}/simpleauth-${DEPLOYMENT}.json"

  if [[ -d "$(dirname "$policy_dir")" ]] || command -v "$name" &>/dev/null; then
    mkdir -p "$policy_dir"

    # For Allowlist/Whitelist, Chrome uses the LAST value seen across files.
    # So we need to merge all SimpleAuth URIs into one comma-separated string.
    # Collect existing URIs from other simpleauth-*.json files
    local existing_uris=""
    for f in "${policy_dir}"/simpleauth-*.json; do
      [[ -f "$f" ]] || continue
      if command -v python3 &>/dev/null; then
        local uri=$(python3 -c "import json; d=json.load(open('$f')); print(d.get('AuthServerAllowlist',''))" 2>/dev/null)
        if [[ -n "$uri" && "$uri" != "${AUTH_URI}" ]]; then
          existing_uris="${existing_uris},${uri}"
        fi
      fi
    done
    local all_uris="${AUTH_URI}${existing_uris}"

    cat > "$policy_file" << CREOF
{
  "AuthServerAllowlist": "${all_uris}",
  "AuthNegotiateDelegateAllowlist": "${all_uris}",
  "DisableAuthNegotiateCnameLookup": true,
  "AuthServerWhitelist": "${all_uris}",
  "AuthNegotiateDelegateWhitelist": "${all_uris}"
}
CREOF
    ok "$name: policy written → ${policy_file}"
  else
    info "$name: not installed (skipped)"
  fi
}

echo ""
info "Configuring browser negotiate-auth for: ${AUTH_URI}"
echo ""

# --- Firefox ---
# Standard package install
configure_firefox "firefox" "/etc/firefox/policies"
# Alternative path (some distros)
[[ -d "/usr/lib/firefox/distribution" ]] && configure_firefox "firefox" "/usr/lib/firefox/distribution"
[[ -d "/usr/lib64/firefox/distribution" ]] && configure_firefox "firefox" "/usr/lib64/firefox/distribution"

# Firefox Snap
if [[ -d "/snap/firefox" ]]; then
  SNAP_POLICY="/etc/firefox/policies"
  mkdir -p "$SNAP_POLICY"
  if [[ ! -f "${SNAP_POLICY}/policies.json" ]]; then
    configure_firefox "firefox-snap" "$SNAP_POLICY"
  fi
  ok "Firefox Snap: policy dir created (may need snap restart)"
fi

# Firefox Flatpak
FLATPAK_FF="/var/lib/flatpak/app/org.mozilla.firefox"
if [[ -d "$FLATPAK_FF" ]]; then
  warn "Firefox Flatpak detected — Kerberos SSO may not work in sandboxed Flatpak"
  warn "  Consider using the system Firefox package instead"
fi

# Firefox ESR
[[ -d "/usr/lib/firefox-esr/distribution" ]] && configure_firefox "firefox-esr" "/usr/lib/firefox-esr/distribution"

# --- Chrome ---
configure_chromium_based "google-chrome" "/etc/opt/chrome/policies/managed"
configure_chromium_based "google-chrome-stable" "/etc/opt/chrome/policies/managed"

# --- Chromium ---
configure_chromium_based "chromium" "/etc/chromium/policies/managed"
configure_chromium_based "chromium-browser" "/etc/chromium-browser/policies/managed"

# --- Microsoft Edge ---
configure_chromium_based "microsoft-edge" "/etc/opt/edge/policies/managed"
configure_chromium_based "microsoft-edge-stable" "/etc/opt/edge/policies/managed"

# --- Brave ---
configure_chromium_based "brave-browser" "/etc/brave/policies/managed"

# --- Vivaldi ---
configure_chromium_based "vivaldi" "/etc/opt/vivaldi/policies/managed"
configure_chromium_based "vivaldi-stable" "/etc/opt/vivaldi/policies/managed"

# --- Opera ---
configure_chromium_based "opera" "/etc/opt/opera/policies/managed"

# ═══════════════════════════════════════════
#  Step 4: Test Kerberos SSO
# ═══════════════════════════════════════════
step "4/4" "Test Kerberos configuration"

# DNS check
if command -v nslookup &>/dev/null; then
  if nslookup "$KDC" &>/dev/null; then
    ok "KDC ($KDC) is reachable via DNS"
  else
    warn "KDC ($KDC) not resolvable — check DNS or /etc/hosts"
  fi
elif command -v host &>/dev/null; then
  if host "$KDC" &>/dev/null; then
    ok "KDC ($KDC) is reachable via DNS"
  else
    warn "KDC ($KDC) not resolvable — check DNS or /etc/hosts"
  fi
fi

# Interactive test
echo ""
echo -e "  ${BOLD}Test Kerberos login${NC}"
echo ""
echo -e "  Enter your Active Directory username (sAMAccountName)."
echo -e "  This is the username you use to log into Windows (e.g. ${CYAN}jsmith${NC})."
echo ""
read -p "  AD username (or press Enter to skip): " AD_USER

if [[ -n "$AD_USER" ]]; then
  KRB_PRINCIPAL="${AD_USER}@${REALM}"
  echo ""
  info "Running: kinit ${KRB_PRINCIPAL}"
  echo ""

  if kinit "$KRB_PRINCIPAL"; then
    echo ""
    ok "kinit succeeded for ${KRB_PRINCIPAL}"
    klist && ok "Ticket cache verified"

    # Test SSO against SimpleAuth
    echo ""
    info "Testing SSO against SimpleAuth..."
    if command -v curl &>/dev/null; then
      HTTP_CODE=$(curl -sk -o /dev/null -w '%{http_code}' --negotiate -u : "https://${AUTH_HOSTNAME}${AUTH_BASE_PATH}/api/auth/negotiate" 2>/dev/null || echo "000")
      if [[ "$HTTP_CODE" == "200" ]]; then
        ok "SSO authentication successful!"
      elif [[ "$HTTP_CODE" == "401" ]]; then
        warn "SSO returned 401 — ticket may not match the SPN"
        warn "  Expected SPN: HTTP/${AUTH_HOSTNAME}"
        warn "  Run: ${CYAN}KRB5_TRACE=/dev/stderr curl -k --negotiate -u : https://${AUTH_HOSTNAME}${AUTH_BASE_PATH}/api/auth/negotiate${NC}"
      elif [[ "$HTTP_CODE" == "000" ]]; then
        warn "Could not reach SimpleAuth at https://${AUTH_HOSTNAME}${AUTH_BASE_PATH}"
      else
        warn "SSO returned HTTP $HTTP_CODE"
      fi
    else
      warn "curl not installed — cannot test SSO endpoint"
    fi
  else
    echo ""
    fail "kinit failed for ${KRB_PRINCIPAL}"
    echo ""
    echo -e "  ${BOLD}Troubleshooting:${NC}"
    echo -e "    • Check the password is correct"
    echo -e "    • Check KDC is reachable: ${CYAN}ping ${KDC}${NC}"
    echo -e "    • Check DNS: ${CYAN}nslookup ${KDC}${NC}"
    echo -e "    • Verbose kinit: ${CYAN}KRB5_TRACE=/dev/stderr kinit ${KRB_PRINCIPAL}${NC}"
  fi
else
  info "Skipped — you can test later with:"
  echo -e "    ${CYAN}kinit your_ad_username@${REALM}${NC}"
fi

# ═══════════════════════════════════════════
#  Summary
# ═══════════════════════════════════════════
echo ""
echo -e "${CYAN}${BOLD}  ════════════════════════════════════════════${NC}"
echo -e "${CYAN}${BOLD}       Setup Complete${NC}"
echo -e "${CYAN}${BOLD}  ════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BOLD}What was configured:${NC}"
echo -e "    • /etc/krb5.conf — Kerberos realm ${REALM}"
echo -e "    • Browser policies — negotiate-auth for ${AUTH_URI}"
echo ""
echo -e "  ${BOLD}Next steps:${NC}"
echo -e "    1. Each user runs: ${CYAN}kinit user@${REALM}${NC}"
echo -e "    2. Open browser → ${CYAN}https://${AUTH_HOSTNAME}${AUTH_BASE_PATH}/login${NC}"
echo -e "    3. Click ${BOLD}Sign in with SSO${NC} — should log in automatically"
echo ""
echo -e "  ${BOLD}Troubleshooting:${NC}"
echo -e "    • ${CYAN}klist${NC} — verify you have a valid ticket"
echo -e "    • ${CYAN}kinit -V user@${REALM}${NC} — verbose kinit for debugging"
echo -e "    • ${CYAN}KRB5_TRACE=/dev/stderr curl --negotiate -u : https://${AUTH_HOSTNAME}${AUTH_BASE_PATH}/api/auth/negotiate${NC}"
echo -e "    • Restart browser after policy changes"
echo -e "    • Flatpak browsers may not support system Kerberos tickets"
echo ""
echo -e "  ${BOLD}To undo:${NC}"
echo -e "    • Restore /etc/krb5.conf from backup (ls /etc/krb5.conf.backup.*)"
echo -e "    • Delete browser policy files (see paths above)"
echo ""
`
}
